# Generated by Django 3.0 on 2019-12-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=100)),
                ('Time', models.CharField(max_length=100)),
                ('RTCTemp', models.FloatField(max_length=100)),
                ('Temp', models.FloatField(max_length=100)),
                ('Humidity', models.FloatField(max_length=100)),
                ('Pressure', models.FloatField(max_length=100)),
                ('PM2_5', models.FloatField(max_length=100)),
                ('PM10', models.FloatField(max_length=100)),
            ],
            options={
                'db_table': 'station',
            },
        ),
    ]
